### ISSUE TITLE
Properties update: lbh15 linking

### ISSUE THREAD

**Issue by fpepe-polito** [newcleo-dev-team/dassh_nc#1]
Up to now, coolant properties are computed and updated by means of linear
interpolation of tabulated values (ex. file `lead.csv` in the `data` folder)
or defined by the user in the input file.
All the tables in the `data` folder are obtained by means of correlations
[1], and properties are calculated at a few specific temperatures. The
following concerns have been identified:
- Since the temperature difference between successive values in tables is
  large (50 K), linear interpolation (as the one performed in the code) is
  less accurate.
- Some of the properties are given at temperatures outside of the validity
  range suggested for that specific correlation in [1]. In Tables 1-3,
  DASSH properties' range is compared to the validity range provided
  by the [2] for each correlation. Please, consider that information
  provided by the SCK reference coincides with those provided by the
  OECD/NEA Handbook [2].
- In Figure 1c, DASSH viscosity shows a discontinuous behavior, due to the
  approximation to 1e-3. Approximation in the tabulated values of viscosity
  leads to large relative errors when compared to the value given by the
  SCK correlation, as plotted in Figure 2.  
- The values for the conductivity of LBE are not in accordance with the
  correlation in the reference, as shown in Figure 1d and Figure 3.  
  
Given the issues presented above, linking DASSH to the properties' library
`lbh15` [3] can be performed for lead, bismuth and LBE, in order to obtain more
accurate values for properties, to correct uncertain values (conductivity for
LBE) and to adhere to the correct validity ranges by providing a warning
each time the evaluation of the properties is required outside them.
 
|   LEAD        | DASSH range [K]  | Correlation NEA   | Validity range [K]   |
| ------------- | ---------------- | ----------------- | -------------------- | 
| Density       | 600 - 2000       | Sobolev 2008a     |     600.60 - 2021    |
| Specific heat | 600 - 2000       | gurvich1991       |     600.60 - 2000    |
| Viscosity     | 600 - 2000       | Sobolev 2007b     |     600.60 - 1473    |
| Conductivity  | 600 - 2000       | Sobolev 2007b     |     600.60 - 1300    |

Table 1: DASSH range of temperatures vs SCK vality range for lead properties. 
 
|     LBE       | DASSH range [K]  | Correlation NEA   | Validity range [K] |
| ------------- | ---------------- | ----------------- | ------------------ |
| Density       | 400 - 1800       | OECD/NEA Handbook | 398 - 1927         |
| Specific heat | 400 - 1800       | Sobolev 2011      | 400 - 1927         |
| Viscosity     | 400 - 1800       | Sobolev 2007b     | 398 - 1300         |
| Conductivity  | 400 - 1800       | Sobolev 2011      | 398 - 1200         |

Table 2: DASSH range of temperatures vs actual vality range for LBE properties.

|   BISMUTH     | DASSH range [K] | Correlation NEA   | Validity range [K]  |
| ------------- | --------------- | ----------------- | ------------------- |
| Density       | 500 - 1800      | Imbeni 1998a      | 544.60 - 1831       |
| Specific heat | 500 - 1800      | Imbeni 1998a      | 544.60 - 1831       |
| Viscosity     | 500 - 1800      | Lucas 1984b       | 544.60 - 1300       |
| Conductivity  | 500 - 1800      | Touloukian 1970b  | 544.60 - 1000       |

Table 3: DASSH range of temperatures vs actual vality range for bismuth properties.

![properties_subplot](https://github.com/user-attachments/assets/733a53ea-302a-47ad-a573-cab1d0432a47)
Figure 1: properties: DASSH vs lbh15.  

![err_visc](https://github.com/user-attachments/assets/afe5b303-507b-429d-8321-28a955015c84)
Figure 2: viscosity relative error: DASSH vs lbh15.

![err_k](https://github.com/user-attachments/assets/f4b14526-73ff-4537-ae83-bac8d183ac58)
Figure 3: thermal conductivity for LBE relative error: DASSH vs lbh15.  

 [1] https://inis.iaea.org/collection/NCLCollectionStore/_Public/43/095/43095088.pdf  
 [2] C. Fazio et Al. Handbook on Lead-bismuth Eutectic Alloy and Lead Properties, 
Materials Compatibility, Thermal-hydraulics and Technologies. Technical Report No. 7268,
 OECD/Nuclear Energy Agency (NEA), Paris, France, 2015. doi:10.1787/42dcd531-en.   
 [3] https://newcleo-dev-team.github.io/lbh15/

**Comment by lelaus** [comment]
New tests implemented in 69f62d2 work appropriately.
Please, @fpepe-polito improve their structure to avoid hard-coded values and automatize the management of all the available materials.

**Comment by fpepe-polito** [comment]
Property tables for lead, lbe and bismuth have been updated in d246ebb. Main changes are: 
- only values within the validity range have been considered;
- precision is improved by including more significant digits (expecially for viscosity);
- values for lbe thermal conductivity have been computed again using Sobolev 2011, and corrected.

**Comment by lelaus** [comment]
All the requests about the link to _lbh15_ package have been managed.
Tests have been modified accordingly.

**Comment by lelaus** [comment]
The link to _lbh15_ does not cover all the available features. In particular, DASSH should allow the user to select which correlations of _lbh15_ to use.

**Comment by fpepe-polito** [comment]
In commit 170c4f4, the way lbh15 is used to define and update material properties has been improved. An instance of `Lead` / `Bismuth` / `LBE` class is no longer created each time `update()` is called. The use of lbh15 is now outside the  `update()` method of class `Material`, which has been restored to the original version. In particular, the `_define_from_lbh15()` method has been added as an alternative to `_define_from_coeff()` and `_define_from_table()`. Similarly to the definition from coefficients or tables, a class `_Matlbh15()` for lbh15 has been introduced. 
Moreover, the possibility for the user to choose the preferred correlation among the ones available in lbh15 has been added. The name of the correlation can now be given in the input file in the `[Materials][[lbh15_correlations]]` section.
Given the changes described above, a new estimation of the computational time has been performed. As shown in the graphs below, the perfomance has been significantly improved, since the computational cost of using lbh15 is the same order of magnitude of table interpolation.

![average_time_lead_](https://github.com/user-attachments/assets/80817bd7-2bad-4861-a127-4ac544182e1a)

![average_time_lbe_](https://github.com/user-attachments/assets/9fe3b8f4-d859-4282-a82d-648a180a3b66)

![average_time_bismuth_](https://github.com/user-attachments/assets/14bb80da-07cd-49e0-8fac-04f716bbf313)

**Comment by lelaus** [comment]
This issue is closed by #5.
