### ISSUE TITLE
Wrong density value in sodium table

### ISSUE THREAD

**Issue by fpepe-polito** [newcleo-dev-team/dassh_nc#7]
Values reported at 2469 K and 2500 K for sodium density in table seem to be wrong. They are not in accordance with reference correlation and even in the table in reference these values are different. Reference table can be found in Table 1.3-1 pag. 87 in [1].
Last two rows of density column should be substituted (empty at 2469 K, 239 kg/m^3 at 2500 K).

[1] J. K. Fink and L. Leibowitz, "Thermodynamic and Transport Properties of Sodium Liquid and Vapor," ANL-RE-95-2, Argonne National Laboratory, 1995.

**Comment by fpepe-polito** [comment]
This issue is being addressed in #4.

**Comment by lelaus** [comment]
Bug fixed in issue #4 .
